# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    ignore:
      - dependency-name: "cumulus-*"
      - dependency-name: "substrate-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "pallet-*"
      - dependency-name: "try-runtime-*"
    schedule:
      interval: "daily"

  - package-ecosystem: "yarn"
    directory: "/ts-tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/ts-tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
