mod frame_system_weight;
mod pallet_airdrop_weight;
mod pallet_assets_weight;
mod pallet_balances_weight;
mod pallet_collective_weight;
mod pallet_contracts_weight;
mod pallet_democracy_weight;
mod pallet_grandpa_weight;
mod pallet_identity_weight;
mod pallet_indices_weight;
mod pallet_membership_weight;
mod pallet_multisig_weight;
mod pallet_preimage_weight;
mod pallet_proxy_weight;
mod pallet_scheduler_weight;
mod pallet_timestamp_weight;
mod pallet_tips_weight;
mod pallet_utility_weight;
mod pallet_vesting_weight;

pub use frame_system_weight::WeightInfo as SystemWeightInfo;
pub use pallet_airdrop_weight::WeightInfo as AirdropWeightInfo;
pub use pallet_assets_weight::WeightInfo as AssetsWeightInfo;
pub use pallet_balances_weight::WeightInfo as BalancesWeightInfo;
pub use pallet_collective_weight::WeightInfo as CollectiveWeightInfo;
pub use pallet_contracts_weight::WeightInfo as ContractsWeightInfo;
pub use pallet_democracy_weight::WeightInfo as DemocracyWeightInfo;
pub use pallet_grandpa_weight::WeightInfo as GrandpaWeightInfo;
pub use pallet_identity_weight::WeightInfo as IdentityWeightInfo;
pub use pallet_indices_weight::WeightInfo as IndicesWeightInfo;
pub use pallet_membership_weight::WeightInfo as MembershipWeightInfo;
pub use pallet_multisig_weight::WeightInfo as MultisigWeightInfo;
pub use pallet_preimage_weight::WeightInfo as PreimageWeightInfo;
pub use pallet_proxy_weight::WeightInfo as ProxyWeightInfo;
pub use pallet_scheduler_weight::WeightInfo as SchedulerWeightInfo;
pub use pallet_timestamp_weight::WeightInfo as TimestampWeightInfo;
pub use pallet_tips_weight::WeightInfo as TipsWeightInfo;
pub use pallet_utility_weight::WeightInfo as UtilityWeightInfo;
pub use pallet_vesting_weight::WeightInfo as VestingWeightInfo;
