
//! Autogenerated weights for `pallet_airdrop`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-02, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-10-175`, CPU: `Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/ice-node
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_airdrop
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/frost/src/weights/pallet_airdrop_weight.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_airdrop`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_airdrop::WeightInfo for WeightInfo<T> {
	// Storage: Airdrop ServerAccount (r:1 w:1)
	fn set_airdrop_server_account() -> Weight {
		// Minimum execution time: 34_848 nanoseconds.
		Weight::from_ref_time(35_199_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Airdrop AirdropChainState (r:1 w:1)
	fn update_airdrop_state() -> Weight {
		// Minimum execution time: 33_229 nanoseconds.
		Weight::from_ref_time(34_361_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Airdrop AirdropChainState (r:1 w:0)
	// Storage: Airdrop MerkleRoot (r:1 w:0)
	// Storage: Airdrop IconSnapshotMap (r:1 w:1)
	// Storage: Airdrop IceIconMap (r:1 w:1)
	// Storage: Airdrop CreditorAccount (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: Vesting Vesting (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	fn dispatch_user_claim() -> Weight {
		// Minimum execution time: 300_150 nanoseconds.
		Weight::from_ref_time(314_968_000)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	// Storage: Airdrop AirdropChainState (r:1 w:0)
	// Storage: Airdrop ExchangeAccountsMap (r:1 w:0)
	// Storage: Airdrop MerkleRoot (r:1 w:0)
	// Storage: Airdrop CreditorAccount (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: Airdrop IconSnapshotMap (r:1 w:1)
	// Storage: Airdrop IceIconMap (r:1 w:1)
	// Storage: Vesting Vesting (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	fn dispatch_exchange_claim() -> Weight {
		// Minimum execution time: 177_925 nanoseconds.
		Weight::from_ref_time(181_012_000)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	// Storage: Airdrop MerkleRoot (r:1 w:1)
	fn change_merkle_root() -> Weight {
		// Minimum execution time: 39_642 nanoseconds.
		Weight::from_ref_time(40_834_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
