#![cfg_attr(not(feature = "std"), no_std)]

mod weights;

pub use weights::*;

// [ pallet_assets,Assets]
// [ pallet_balances,Balances]
// [ pallet_bounties,Bounties]
// [ pallet_collective,Council]
// [ pallet_collective,TechnicalCommittee]
// [ pallet_contracts,Contracts]
// [ pallet_democracy,Democracy]
// [ pallet_elections_phragmen,PhragmenElection]
// [ pallet_evm,EVM]
// [ pallet_grandpa,Grandpa]
// [ pallet_identity,Identity]
// [ pallet_indices,Indices]
// [ pallet_membership,CouncilMembership]
// [ pallet_membership,TechnicalMembership]
// [ pallet_multisig,Multisig]
// [ pallet_preimage,Preimage]
// [ pallet_proxy,Proxy]
// [ pallet_scheduler,Scheduler]
// [ pallet_timestamp,Timestamp]
// [ pallet_tips,Tips]
// [ pallet_treasury,Treasury]
// [ pallet_utility,Utility]
// [ pallet_vesting,Vesting]
// [ pallet_airdrop,Airdrop]
