name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-08-14
        target: x86_64-unknown-linux-gnu
        components: rustfmt, clippy
        default: true
    - name: Install WASM target (for runtime building)
      shell: bash
      run: rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-14
    - name: Build optimized binary
      uses: actions-rs/cargo@v1
      with:
        command: build
