name: Bump release tag version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release type (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: ${{ github.event.inputs.version }}

      #  Similar action, it can be an alternative for the anothrNick/github-tag-action
      #
      #      - name: Bump version and push tag
      #        id: tag_version
      #        uses: mathieudutour/github-tag-action@v6.0
      #        with:
      #          github_token: ${{ secrets.GITHUB_TOKEN }}
      #          default_bump: ${{ github.event.inputs.version }}